repos:
  - repo: local
    hooks:
      - id: run-pre-commit-on-all-files
        name: Run pre-commit on all files
        entry: pre-commit run --all-files
        language: system
        always_run: true

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3.12

  # flake8 - linting
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8

  # isort - sorting imports
  - repo: https://github.com/pycqa/isort
    rev: 5.13.0
    hooks:
      - id: isort
